### ISSUE TITLE
ssh key not found in directory when it does in fact exist

### ISSUE THREAD

**Issue by Scarycrumb45** [Megapixel99/GAM#57]
Running `ls /home/user/.ssh/`
gives
`id_rsa  id_rsa.pub  id_rsa_Scarycrumb45  id_rsa_Scarycrumb45.pub  known_hosts`

Full Error:
```
Adding SSH Keys to the SSH authentication agent...
/usr/local/lib/node_modules/git-alias-manager/src/methods.js:187
  throw (new Error(`File: id_rsa_${alias} not found in directory: ${dir}`));
         ^

Error: File: id_rsa_Scarycrumb45 not found in directory: /home/user/.ssh
    at Object.addSshKeyAgent (/usr/local/lib/node_modules/git-alias-manager/src/methods.js:187:10)
    at /usr/local/lib/node_modules/git-alias-manager/src/manager.js:35:21
    at async /usr/local/lib/node_modules/git-alias-manager/src/manager.js:33:5
```

**Comment by Megapixel99** [comment]
What OS are you using (i.e. are you using a Mac, or a Linux distribution)?

**Comment by Scarycrumb45** [comment]
Debian based Linux

**Comment by Megapixel99** [comment]
Hi, sorry for the late response, I've been busy recently.

Did you make the key  id_rsa_Scarycrumb45 with GAM, or did you run the commands to make the ssh key independent of GAM?

Is `/home/user` set to your home directory?

**Comment by Megapixel99** [comment]
Closing due to not receiving a response from requester.
